apiVersion: v1
kind: pod
metadata:
  name: limit
spec: 
  containers:
  - name: nginx
    image: nginx
    resource:
      reqiuests:
        cpu: 100m
        memmory: 68mi
      limits:
        cpu: 120m
        memory: 100mi

